### ISSUE TITLE
部分历史菜价补遗/更新

### ISSUE THREAD

**Issue by yqt** [doylecnn/NewNSFCbot#1]
# 现状

case: 当前时间礼拜三下午(153)，目标更新礼拜天上午(105)、礼拜三上午菜价(145)，礼拜一和礼拜二菜价因错过查看时间未知。

当前实现该目标，可选指令为`/weekprice`，参数如下：
```
/weekprice 105,0,0,0,0,0,145,153
```

# 问题
- 对于补充一两个数据来说，输入比较繁琐
- 中间不存在值（礼拜天下午）和未知值为0严格上来说并不准确 ~~（强迫证）~~

# 建议

`/dtcj PRICE [DATE] [PRICE DATE ... ]` 添加可选参数DATE(repeated)，如：

- 更新礼拜天(上午)菜价
```
/dtcj 105 SUN
/dtcj 105 SUN_AM
```
- 更新礼拜三上午菜价
```
/dtcj 145 WED_AM
```
- 更新礼拜一下午及三上午菜价
```
/dtcj 100 MON_AM 145 WED_AM
```

**Comment by doylecnn** [comment]
已实现建议中的使用 dtcj 指令 补报菜价方案，大小写不限
同时解决了 weekprice 指令 中，未知值是0的问题——现在可以接受 `/weekprice 105,,,,,,145,153` 这样的形式
